import { Roboto } from 'next/font/google'
import './globals.css'

import type { Metadata } from 'next'
import { Header } from '@/components/base/header'
import { Footer } from '@/components/base/footer'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const roboto = Roboto({
	weight: ['100', '300', '400', '500', '700', '900'],
	subsets: ['latin', 'cyrillic', 'cyrillic-ext'],
	display: 'swap',
	variable: '--font-roboto',
})

type RootLayoutProps = {
	children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
	return (
		<html lang='ru' className='h-full w-full'>
			<body
				className={`${roboto.variable} font-roboto h-full w-full bg-sky-100 flex flex-col gap-10`}
			>
				<Header />
				<main className='w-full flex-1'>{children}</main>
				<Footer />
			</body>
		</html>
	)
}
