# Generated by Django 5.1 on 2024-09-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='SiteName', max_length=255, verbose_name='Название сайта')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='', verbose_name='Иконка в браузере')),
                ('logo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Логотип сайта')),
                ('palette', models.CharField(blank=True, max_length=255, null=True, verbose_name='Палитра')),
                ('typography', models.CharField(blank=True, max_length=255, null=True, verbose_name='Типография')),
                ('news', models.BooleanField(default=False, verbose_name='Включить Новости')),
                ('groups', models.BooleanField(default=False, verbose_name='Включить Группы')),
                ('events', models.BooleanField(default=False, verbose_name='Включить Мероприятия')),
            ],
            options={
                'verbose_name': 'НАСТРОЙКИ САЙТА',
                'verbose_name_plural': 'НАСТРОЙКИ САЙТА',
            },
        ),
    ]
