services:
    portal-backend:
        image: aniwoov/portal-backend:deploy-1.1.0
        ports:
            - "8000:8000"
        networks:
            - portal
        environment:
            - SECRET_KEY=django-insecure-e!&uwx-=vcc1tl0xu_5lfsq8k8t#+=5t+yw3dxdgy!)-divt)!
            - DEBUG=true
            - ALLOWED_HOSTS=*
            - EMAIL_HOST_USER=Denns2002
            - EMAIL_HOST_PASSWORD=lujukxqmltgjvyza
        command: bash -c "python manage.py sendadmincreds; python manage.py runserver 0.0.0.0:8000"
    portal-frontend:
        image: aniwoov/portal-frontend:deploy-1.1.0
        ports:
            - "3000:3000"
        networks:
            - portal
        environment:
            - API_BASE_URL=http://portal-backend:8000
        command: yarn start -p 3000

networks:
    portal:
