# Generated by Django 5.1 on 2024-08-10 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verification', models.BooleanField(default=False)),
                ('is_change_password', models.BooleanField(default=False)),
                ('is_change_email', models.BooleanField(default=False)),
                ('is_reset_password', models.BooleanField(default=False)),
                ('is_error', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('from_email', models.CharField(blank=True, default='Denns2002@yandex.ru', max_length=255, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('to_emails', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mailing',
                'verbose_name_plural': 'Mailings',
            },
        ),
    ]
